config/routes.rb
Rails.application.routes.draw do
  root 'rooms#default'

  resource :session, only: [:new, :create, :destroy]

  resources :rooms, param: :name, only: [:show, :new, :create] do
    collection do
      get 'default'
    end
  end

end

app/models/room.rb
class Room < ActiveRecord::Base
  validates :name, presence: true
  has_and_belongs_to_many :users
end

app/models/user.rb
class User < ActiveRecord::Base
  validates :name, presence: true
  has_and_belongs_to_many :rooms
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    session[:user_id] && User.find(session[:user_id])
  end
  helper_method :current_user

  def all_rooms
    Room.all
  end
  helper_method :all_rooms
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_filter :require_current_user

  def show
    @other_users = current_room.users.reject{|u| u == current_user}
  end

  def new
    @room = Room.new
  end

  def create
    new_room = Room.create(name: params[:room][:name])
    redirect_to room_path(new_room.name)
  end

  def default
    redirect_to room_path(default_room.name)
  end

private

  def default_room
    Room.first_or_create(name: 'home')
  end

  def current_room
    @current_room ||= Room.find_by(name: params[:name])
  end
  helper_method :current_room

  def require_current_user
    redirect_to new_session_path unless current_user
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  before_action :find_or_create_user, only: :create

  layout "no_menu"

  def new
  end

  def create
    session[:user_id] = @user.id
    redirect_to(params[:return_to] || root_path)
  end

  def destroy
    session[:user_id] = nil
    redirect_to(root_path)
  end

  private

  def find_or_create_user
    @user = User.find_or_create_by(name: params[:name])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatapp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= yield :tail_javascript %>
</body>
</html>

app/views/layouts/no_menu.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Chatapp</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

<%= yield :tail_javascript %>
</body>
</html>

app/views/messages/index.html.erb
Welcome, <%= current_user.name %>! <%= link_to('Log out', 'session', method: :delete) %>

<div id="updates" data-current-user="<%= current_user.name %>"></div>
<div id="typing"></div>

<p>
  <label>receiver</label>
  <select id="receivers" name="receiver">
    <option>all</option>
  </select>
</p>

<p>
  <textarea id="content" name="content" rows="8" cols="80"></textarea>
</p>

<p>
  <button id="send">Send</button>
</p>

<% content_for :tail_javascript do %>
  <%= javascript_include_tag 'messages' %>
<% end %>

app/views/rooms/new.html.erb
<h3>Add a chat room</h3>
<%= form_for @room do |f| %>
  <%= f.label :name %>:
  <%= f.text_field :name %>

  <%= f.submit %>
<% end %>

app/views/rooms/show.html.erb
<div id="updates" data-current-user="<%= current_user.name %>"></div>
<div id="typing"></div>

<p>
  <label>receiver</label>
  <select id="receivers" name="receiver">
    <option>all</option>
    <% @other_users.each do |user| %>
      <option><%= user.name %></option>
    <% end %>
  </select>
</p>

<p>
  <textarea id="content" name="content" rows="8" cols="80"></textarea>
</p>

<p>
  <button id="send">Send</button>
</p>

<% content_for :tail_javascript do %>
  <%= javascript_include_tag 'messages' %>
<% end %>

app/views/shared/_header.html.erb
<div id="header">
  Welcome, <%= current_user.name %>! <%= link_to('Log out', '/session', method: :delete) %>
</div>

app/views/shared/_left_menu.html.erb
<div id="left-menu">
  <h5>Rooms:</h5>
  <ul>
    <% all_rooms.each do |room| %>
      <% if current_room == room %>
        <li id='current-room'><%= room.name %></li>
      <% else %>
        <li><%= link_to(room.name, room_path(room.name)) %></li>
      <% end %>
    <% end %>
  </ul>
  <%= link_to("Add room", new_room_path, class: 'new-room') %>
</div>